#!/usr/bin/env bash

set -e

CONFIG_DIR=$1

if [[ -z $CONFIG_DIR ]]
then
  echo "Usage: setup_syslog_forwarder [config dir]"
  exit 1
fi

cp $CONFIG_DIR/syslog_forwarder.conf /etc/rsyslog.d/00-syslog_forwarder.conf

# warden stemcells currently run an older version of rsyslog (7.4.6),
# which requires imfile.so to exist in the /usr/local/lib/rsyslog dir
# newer, non-warden stemcells do not have this dir
if [ -d /usr/local/lib/rsyslog/ ]; then
  ln -fs /usr/lib/rsyslog/imfile.so /usr/local/lib/rsyslog/imfile.so
fi

chmod 755 /var/vcap/data/sys/
chmod 755 /var/vcap/data/sys/log/

/usr/sbin/service rsyslog restart
