source 'https://rubygems.org'

gem 'bosh_cli'
gem 'rake', '~> 10.3'
gem 'rabbitmq_http_api_client', '~> 1.3.0'
gem 'bosh-template'
gem 'httparty'
gem 'pry-byebug'
gem 'rspec','~> 3.3'
gem 'rspec-instafail', '~> 1.0'
gem 'bunny', '~> 1.6.3'
gem 'mqtt',  '~> 0.1.0'
gem 'stomp', '~> 1.3.1'
gem 'prof', '~> 0.31.15'
gem 'hula', :git => "git://github.com/pivotal-cf-experimental/hula", :branch => "ca_cert"
gem 'rspec-retry'
gem 'papertrail'
