#!/bin/bash -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script expects to live two directories below the base directory.
BASE_DIR="$( cd "${MY_DIR}/../.." && pwd )"

pushd "${BASE_DIR}"
  eval `ssh-agent -s`

  chmod 600 ../git-london-meta/credentials/id_rsa_cfintegration
  ssh-add ../git-london-meta/credentials/id_rsa_cfintegration

  bundle install --path vendor/bundle
  export SKIP_ERRANDS=true
  bundle exec rspec spec/upgrade-tests/check_cluster_status_spec.rb
popd

