#!/bin/bash -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script expects to live two directories below the base directory.
BASE_DIR="$( cd "${MY_DIR}/../../../${GIT_REPO}" && pwd )"

VERSION="$( cat release-version/number )"

pushd "${BASE_DIR}/"
  bosh -n create release --force --with-tarball --name ${NAME} --version ${VERSION}
popd
