#!/bin/bash -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script expects to live two directories below the base directory.
BASE_DIR="$( cd "${MY_DIR}/../.." && pwd )"

pushd "${BASE_DIR}"
  RANDOM_STRING="$(cat ../$RANDOM_STRING_FILE)"

  CF_ORG="test-org-${RANDOM_STRING}"
  SG_NAME="allow-all-sg-${RANDOM_STRING}"

  cf api --skip-ssl-validation $CF_API
  cf auth $CF_USERNAME $CF_PASSWORD

  cf delete-security-group $SG_NAME -f

  cf delete-org $CF_ORG -f
popd

