#!/bin/bash -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script expects to live two directories below the base directory.
BASE_DIR="$( cd "${MY_DIR}/../.." && pwd )"

pushd "${BASE_DIR}"
  RANDOM_STRING="$(cat ../$RANDOM_STRING_FILE)"

  CF_ORG="test-org-${RANDOM_STRING}"
  CF_SPACE="test-space-${RANDOM_STRING}"
  SERVICE_INSTANCE_NAME="test-service-${RANDOM_STRING}"
  APP_NAME="test-app-${RANDOM_STRING}"
  SG_RULES_FILE_PATH="/tmp/security_group_rules.json"
  SG_NAME="allow-all-sg-${RANDOM_STRING}"

  cf api --skip-ssl-validation $CF_API
  cf auth $CF_USERNAME $CF_PASSWORD

  cf create-org $CF_ORG
  cf target -o $CF_ORG

  cf create-space $CF_SPACE
  cf target -s $CF_SPACE

  echo -e '[{"destination": "0.0.0.0-255.255.255.255","protocol": "all"}]' > $SG_RULES_FILE_PATH
  cf create-security-group $SG_NAME $SG_RULES_FILE_PATH
  cf bind-security-group $SG_NAME $CF_ORG $CF_SPACE
  cf bind-staging-security-group $SG_NAME
  cf bind-running-security-group $SG_NAME
  rm -f $SG_RULES_FILE_PATH

  cf create-service $SERVICE_NAME $SERVICE_PLAN $SERVICE_INSTANCE_NAME

  cf push $APP_NAME -p system_test/rabbit-example-app --no-start

  cf bind-service $APP_NAME $SERVICE_INSTANCE_NAME

  cf set-env $APP_NAME SERVICE_NAME $SERVICE_NAME

  cf start $APP_NAME
popd
