#!/bin/bash -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script expects to live two directories below the base directory.
BASE_DIR="$( cd "${MY_DIR}/../../.." && pwd )"

DESTINATION="${BASE_DIR}/${OUTPUT_PATH}"

mkdir -p "${DESTINATION}"

STEMCELL_URL=$( curl --retry 5 -f http://bosh.io/api/v1/stemcells/"${STEMCELL_NAME}" | jq -r "map(select(.version == \"${STEMCELL_VERSION}\"))[0] | .light // .regular | .url " )

if [ -z "${STEMCELL_URL}" ]; then
  echo "Couldn't find URL for stemcell"
  exit 1
fi

curl --retry 5 -s -f "${STEMCELL_URL}" -o "${DESTINATION}"/stemcell.tgz


