#!/bin/bash -eu

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script expects to live two directories below the base directory.
BASE_DIR="$( cd "${MY_DIR}/../../.." && pwd )"

pushd ${BASE_DIR}
  RANDOM_STRING="$(cat $RANDOM_STRING_FILE)"
  APP_URI="http://test-app-${RANDOM_STRING}.${CF_DOMAIN}/store"

  EXPECTED="original_message-${RANDOM_STRING}"
  ACTUAL=`curl -s -f -XGET ${APP_URI}`

  echo "Expected message: '$EXPECTED'"
  echo "Actual message: '$ACTUAL'"

  if [ "$EXPECTED" != "$ACTUAL" ]; then
    echo "FAILURE: Did not get original message."
    exit -1
  fi

  echo "SUCCESS"
popd
