#!/bin/bash -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

#This script expects to live two directories below the base directory.
BASE_DIR="$( cd "${MY_DIR}/../.." && pwd )"

pushd "${BASE_DIR}"
  bundle install --path vendor/bundle
  bundle exec bosh -n target ${BOSH_TARGET}
  bundle exec bosh -n login ${BOSH_USERNAME} ${BOSH_PASSWORD}
  bundle exec bosh -n deployment ${BOSH_MANIFEST}
  bundle exec bosh -n run errand ${ERRAND}
popd
