#!/bin/sh
##  The contents of this file are subject to the Mozilla Public License
##  Version 1.1 (the "License"); you may not use this file except in
##  compliance with the License. You may obtain a copy of the License
##  at http://www.mozilla.org/MPL/
##
##  Software distributed under the License is distributed on an "AS IS"
##  basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
##  the License for the specific language governing rights and
##  limitations under the License.
##
##  The Original Code is RabbitMQ.
##
##  The Initial Developer of the Original Code is VMware, Inc.
##  Copyright (c) 2012-2014 VMware, Inc.  All rights reserved.
##

export HOME=/var/vcap/store/rabbitmq # the erlang cookie goes in here
export ERL_INETRC=${HOME}/erl_inetrc # avoid rewriting /etc/hosts

CLEAN_BOOT_FILE=start_clean
SASL_BOOT_FILE=start_sasl

## Set default values

CONFIG_FILE=/var/vcap/store/rabbitmq/etc/rabbitmq/rabbitmq
LOG_BASE=/var/vcap/sys/log/rabbitmq-server
MNESIA_BASE=/var/vcap/store/rabbitmq/mnesia
ENABLED_PLUGINS_FILE=/var/vcap/store/rabbitmq/enabled_plugins

PLUGINS_DIR="${RABBITMQ_HOME}/plugins"
IO_THREAD_POOL_SIZE=64

CONF_ENV_FILE=/var/vcap/store/rabbitmq/etc/rabbitmq/rabbitmq-env.conf
