---
name: ((deployment-name))

releases:
- name: cf-rabbitmq
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: ((stemcell-version))

instance_groups:
- name: rmq
  instances: 3
  jobs:
  - name: rabbitmq-server
    release: cf-rabbitmq
  vm_type: r3.large
  stemcell: default
  persistent_disk_type: 10GB
  networks:
  - name: services
  azs:
  - z1
  - z2

- name: haproxy
  instances: ((haproxy-instances))
  jobs:
  - name: rabbitmq-haproxy
    release: cf-rabbitmq
  vm_type: m3.medium
  stemcell: default
  networks:
  - name: services
  azs:
  - z1
  - z2

properties:
  rabbitmq-server:
    restart_statsdb_cron_schedule: "42 */4 * * *"
    plugins:
    - rabbitmq_management
    - rabbitmq_mqtt
    - rabbitmq_stomp
    ports:
    - 5672
    - 5671
    - 1883
    - 8883
    - 61613
    - 61614
    - 15672
    - 15674
    administrators:
      management:
        username: ((rabbitmq-management-username))
        password: ((rabbitmq-management-password))
      broker:
        username: ((rabbitmq-broker-username))
        password: ((rabbitmq-broker-password))
    cookie: "rabbit-cluster:aws"
    cluster_partition_handling: autoheal
    use_native_clustering_formation: ((use-native-clustering-formation))

  rabbitmq-haproxy:
    stats:
      username: ((haproxy-stats-username))
      password: ((haproxy-stats-password))

update:
  canaries: 1
  canary_watch_time: 30000-180000
  update_watch_time: 30000-180000
  max_in_flight: 4
  serial: false
