#!/bin/bash -e

[ -z "$DEBUG" ] || set -x

GOPATH="${GOPATH:-/go}"
WORKDIR=$GOPATH/src/github.com/pivotal-cf/rabbitmq-upgrade-preparation

mkdir -p "$WORKDIR"
cp -r "$PWD"/rabbitmq-upgrade-preparation/* "$WORKDIR"/
cd "$WORKDIR"
export PATH=$GOPATH/bin:/usr/local/go/bin:$PATH
cd $WORKDIR
go get -u github.com/golang/dep/cmd/dep
dep ensure
scripts/run_tests

