#!/bin/bash
set -ex

. scripts/config/docker_image

docker run --rm \
  -e BUNDLE_GEM__FURY__IO=${BUNDLE_GEM__FURY__IO} \
  -v $PWD:$PWD \
  -v "${PRIVATE_KEY}:/key" \
  -w $PWD \
  $DOCKER_IMAGE \
  bash -c "eval \$(ssh-agent) && chmod 400 /key && ssh-add /key && bundle install && bundle exec rake --trace release_pipeline:build_final_release_in_submodule[${AWS_ACCESS_KEY_ID},${AWS_SECRET_ACCESS_KEY},${GO_PIPELINE_COUNTER}]"

