#!/bin/sh
set -e -x

ROOT_DIR_PATH="$(cd "$(dirname "$0")"/.. && pwd)"
cd "$ROOT_DIR_PATH"

./scripts/check

# Commit submodules changes
echo -n "bump "
for submodule in $(git diff --cached --submodule | grep '^Submodule' | awk '{print $2}'); do
  echo -n "$(basename $submodule) "
done

git submodule status | awk '{print $2}' | xargs git diff --cached --submodule | git ci --file -

git duet-commit --amend --reset-author --verbose

