#!/usr/bin/env bash

set -eu

export BOSH_ENVIRONMENT="${BOSH_ENVIRONMENT:-https://192.168.50.6:25555}"
export BOSH_NON_INTERACTIVE="${BOSH_NON_INTERACTIVE:-false}"
export BOSH_CLIENT="${BOSH_CLIENT:-admin}"
export BOSH_CLIENT_SECRET="${BOSH_CLIENT_SECRET:-admin}"
export BOSH_CA_CERT="${BOSH_CA_CERT:-"$(bosh int ~/deployments/vbox/creds.yml --path /director_ssl/ca)"}"
export BOSH_DEPLOYMENT="${BOSH_DEPLOYMENT:-cf-rabbitmq}"
export BOSH_MANIFEST=${BOSH_MANIFEST:-$(./scripts/generate-manifest)}
export INSTANCE_SSH_KEY_FILE="${PWD}/director.key"

echo -e "${BOSH_INSTANCE_SSH_KEY}" > "${INSTANCE_SSH_KEY_FILE}"
chmod 0600 "${INSTANCE_SSH_KEY_FILE}"

bundle check || bundle install
bundle exec "$@"

