#!/usr/bin/env bash

set -eu

export BOSH_MANIFEST=${BOSH_MANIFEST:-$(./scripts/generate-manifest)}

# Configuration for bosh-cli
export BOSH_ENVIRONMENT="${BOSH_ENVIRONMENT:-https://192.168.50.6:25555}"
export BOSH_NON_INTERACTIVE="${BOSH_NON_INTERACTIVE:-false}"
export BOSH_CLIENT="${BOSH_CLIENT:-admin}"
export BOSH_CLIENT_SECRET="${BOSH_CLIENT_SECRET:-admin}"
export BOSH_CA_CERT="${BOSH_CA_CERT:-"$(bosh int ~/deployments/vbox/creds.yml --path /director_ssl/ca)"}"
export BOSH_DEPLOYMENT="${BOSH_DEPLOYMENT:-cf-rabbitmq}"

# Jumpbox configuration for pcf-tile-pipeline
export JUMPBOX_SSH_KEY="${JUMPBOX_SSH_KEY:-"$(bosh int ~/deployments/vbox/creds.yml --path /jumpbox_ssh/private_key)"}"
export JUMPBOX_URL="${JUMPBOX_URL:-192.168.50.6}"
export JUMPBOX_PORT="${JUMPBOX_PORT:-22}"

# Jumpbox configuraiton for bosh-cli
export JUMPBOX_PRIVATE_KEY
JUMPBOX_PRIVATE_KEY="$(mktemp -t jumpbox.pem.XXX)"
echo "$JUMPBOX_SSH_KEY" > "$JUMPBOX_PRIVATE_KEY"

# pcf-tile-pipeline currently exports BOSH_ALL_PROXY, but it seems not to be working properly.
# We are then overwriting it here.
unset BOSH_ALL_PROXY
export BOSH_ALL_PROXY="ssh+socks5://jumpbox@$JUMPBOX_URL:$JUMPBOX_PORT?private-key=$JUMPBOX_PRIVATE_KEY"

bundle check || bundle install
bundle exec "$@"
