#!/bin/bash -e

[ -z "$DEBUG" ] || set -x

GOPATH="${GOPATH:-/go}"
WORKDIR=$GOPATH/src/github.com/pivotal-cf/rabbitmq-upgrade-preparation

main() {
  setup_workdir
  scripts/setup
  useradd test-user
  chown -R test-user $GOPATH
  su test-user -c 'export PATH=$GOPATH/bin:/usr/local/go/bin:$PATH; cd $WORKDIR; godep get; scripts/run_tests' --preserve-environment
}

setup_workdir() {
  mkdir -p "$WORKDIR"
  cp -r "$PWD"/rabbitmq-upgrade-preparation/* "$WORKDIR"/
  cd "$WORKDIR"
}

main
