#!/bin/bash

set -e

BOSH_TARGET_ALIAS="lite"
WORKSPACE_BASE_DIR="$HOME/workspace"
RELEASE_NAME=rabbitmq

log() {
  local _message=$1
  echo -e "$_message"
}

bosh_target_and_set_deployment() {
  local _bosh_target=$1
  local _bosh_deployment_manifest_path=$2

  bosh target "$_bosh_target"
  bosh deployment "$_bosh_deployment_manifest_path"
}

bosh_deploy() {
  bosh -n deploy
}

bosh_run_errand() {
  local _errand_name=$1

  bosh -n run errand "$_errand_name"
}

check_args() {
  if [ -z $BOSH_MANIFEST ]
  then
    log "Please set the BOSH_MANIFEST environment variable to the path to your manifest file"
    log "E.G. export BOSH_MANIFEST=~/workspace/london-ci-tools/manifests/${RELEASE_NAME}/develop/development/bosh-lite.yml"
    exit 1
  fi

  if [ "$#" -lt 1 ]
  then
    log "[WARN] no BOSH target specified - defaulting to lite"
  else
    BOSH_TARGET_ALIAS=$1
  fi
}

update_release() {
  if [ ! -f scripts/update-release ]
  then
    log "[ERROR] Could not find the 'scripts/update-release' script in $(pwd)"
    exit 1
  fi

  scripts/update-release
}

upload_release() {
  local _release_path=$1

  pushd "$_release_path"
  update_release
  bosh -n create release --force
  bosh -n upload release --rebase || log "[WARN] Attempted a --rebase, but there were no job or package changes."
  popd
}

main() {
  check_args "$@"

  bosh_target_and_set_deployment "$BOSH_TARGET_ALIAS" "$BOSH_MANIFEST"

  upload_release "${WORKSPACE_BASE_DIR}/cf-${RELEASE_NAME}-release"

  bosh_deploy
  bosh_run_errand "broker-registrar"
}

main "$@"
