#!/bin/bash

docker_status=$(boot2docker status)

if [ "$docker_status" != "running" ]; then
  echo -e "Docker is not running. You can start it up by running:\n\nboot2docker start"
  exit 1
fi

set -ex

if [ -z "$DOCKER_IMAGE" ]; then
  DOCKER_IMAGE=cflondonservices/london-services-ci-base
fi

docker_dir=/home/vcap/pivotal-product

manifest_dir=$(cd "${BOSH_MANIFEST%/*}"; echo "$PWD")

bosh_docker_dir=/home/vcap/bosh_manifest

pushd "$(dirname "$0")/.."
  docker run --rm --volume "$PWD":"$docker_dir" \
    --volume "$manifest_dir":"$bosh_docker_dir" \
    --workdir "$docker_dir" \
    -e "BOSH_MANIFEST=$bosh_docker_dir/${BOSH_MANIFEST##*/}" \
    "$DOCKER_IMAGE" \
    bash -c "bundle install && bosh -n target https://192.168.50.4:25555 lite && bosh login admin admin && function be { bundle exec \"\$*\" ; } && eval \"$*\""
popd
