#!/usr/bin/env bash

set -e

export BOSH_MANIFEST=${BOSH_MANIFEST:-$("$HOME/workspace/cf-rabbitmq-release/scripts/interpolate-manifest-for-bosh-lite")}

main() {
  write_keys_to_file
  install_dependencies
  run_integration_tests_individually_to_isolate_state
}

write_keys_to_file() {
  if [[ $BOSH_CERT ]]; then
    echo -e "$BOSH_CERT" > cert.pem
  fi
}

install_dependencies() {
  bundle install
}

run_integration_tests_individually_to_isolate_state() {
  spec_files=($(find spec/integration/ -type f))

  for spec_file in "${spec_files[@]}"
  do
    bundle exec rspec "$spec_file" --fail-fast
  done
}

main
