#!/bin/bash

run_basht_tests() {
  which basht 1>/dev/null 2>&1 || go get github.com/progrium/basht

  local ret=0
  for test in spec/bash/*_test.bash; do
    echo "Test $test"
    basht "$test" || ret=1
  done

  return $ret
}

set_rmq_version() {
  if [ "$(uname -s)" != "Linux" ]; then
    echo "WARNING: dynamic RMQ version only works on Linux..."
  else
    mkdir -p /var/vcap/jobs/rabbitmq-server/etc
    echo "export RMQ_VERSION=3.7" >/var/vcap/jobs/rabbitmq-server/etc/rabbitmq-server-version
  fi
}

set_rmq_version
run_basht_tests
