#!/usr/bin/env bash

set -e
set -o pipefail

main() {
  eval "$(ssh-agent)"
  trap 'kill $SSH_AGENT_PID' EXIT

  set_bosh_manifest
  add_bosh_ssh_key
  write_keys_to_file
  install_dependencies
  get_test_types | run_isolated_tests
}

set_bosh_manifest() {
  if [ -n "$BOSH_MANIFEST" ]
  then
    export BOSH_MANIFEST
    return
  fi

  local generator manifest_file
  generator="$(dirname "$0")/interpolate-manifest-for-bosh-lite"
  manifest_file="$( "$generator" )"

  export BOSH_MANIFEST="$manifest_file"
}

add_bosh_ssh_key() {
  if [ -n "$BOSH_SSH_KEY" ]
  then
    ssh-add "$BOSH_SSH_KEY"
    return
  fi

  local tmp_key_file
  tmp_key_file="$(mktemp)"
  bosh int --path /jumpbox_ssh/private_key ~/deployments/vbox/creds.yml > "$tmp_key_file"
  chmod 0600 "$tmp_key_file"
  ssh-add "$tmp_key_file"
  rm "$tmp_key_file"
}

write_keys_to_file() {
  if [[ $BOSH_CERT ]]; then
    echo -e "$BOSH_CERT" > cert.pem
  fi
}

install_dependencies() {
  bundle install
}

get_test_types() {
  local base_name
  base_name="$( basename "$0" )"

  [[ $base_name =~ 'integration' ]] && echo 'integration'
  [[ $base_name =~ 'system' ]]      && echo 'system'
}

run_isolated_tests() {
  local base_dir
  base_dir="$( dirname "$0" )/.."

  while read -r spec_file
  do
    find "${base_dir}/spec/${spec_file}" -type f -exec echo bundle exec rspec '{}' --fail-fast \;
  done
}

main
