#!/bin/bash
set -ex

. scripts/config/docker_image

export BOSH_MANIFEST=${PWD}/${BOSH_MANIFEST}

docker run --rm \
  -v $PWD:$PWD \
  -v "${BOSH_INSTANCE_SSH_KEY}:/key" \
  -v "${BOSH_MANIFEST}:/manifest" \
  -w $PWD \
  -e PROF_CF_DOMAIN=${PROF_CF_DOMAIN} \
  -e PROF_CF_URL=${PROF_CF_URL} \
  -e PROF_CF_USERNAME=${PROF_CF_USERNAME} \
  -e PROF_CF_PASSWORD=${PROF_CF_PASSWORD} \
  -e BOSH_TARGET=${BOSH_TARGET} \
  -e BOSH_USERNAME=${BOSH_USERNAME} \
  -e BOSH_PASSWORD=${BOSH_PASSWORD} \
  -e BOSH_MANIFEST=/manifest \
  -e BUNDLE_GEM__FURY__IO=${BUNDLE_GEM__FURY__IO} \
  $DOCKER_IMAGE \
  bash -c "eval \$(ssh-agent) && chmod 400 /key && ssh-add /key && bundle install && bundle exec rake --trace spec"

