#!/bin/bash
set -ex

. scripts/config/docker_image

docker run --rm \
  -v $PWD:$PWD \
  -v "${PWD}/${BOSH_INSTANCE_SSH_KEY}:/key" \
  -v "${PWD}/${BOSH_MANIFEST}:/manifest" \
  -w $PWD \
  -e CF_DOMAIN=${CF_DOMAIN} \
  -e CF_API=${CF_API} \
  -e CF_USERNAME=${CF_USERNAME} \
  -e CF_PASSWORD=${CF_PASSWORD} \
  -e BOSH_TARGET=${BOSH_TARGET} \
  -e BOSH_USERNAME=${BOSH_USERNAME} \
  -e BOSH_PASSWORD=${BOSH_PASSWORD} \
  -e BOSH_MANIFEST=/manifest \
  -e BUNDLE_GEM__FURY__IO=${BUNDLE_GEM__FURY__IO} \
  $DOCKER_IMAGE \
  bash -c "eval \$(ssh-agent) && chmod 400 /key && ssh-add /key && bundle install && bundle exec rake --trace spec"

