#!/bin/bash -ex

log() {
  local _message=$1
  echo -e "$_message"
}

check_args() {
  if [ -z "$BOSH_MANIFEST" ]
  then
    log "Please set the BOSH_MANIFEST environment variable to the path to your manifest file"
    log "e.g. export BOSH_MANIFEST=~/workspace/cf-rabbitmq-release/manifests/cf-rabbitmq.yml"
    exit 1
  fi
}

TMP_MANIFEST=/tmp/bosh_manifest.yml

edit_manifest() {
  uuid=$(bosh -t lite status --uuid)
  sed "s/director_uuid: .*/director_uuid: ${uuid}/" "$BOSH_MANIFEST" > "$TMP_MANIFEST"
  BOSH_MANIFEST="$TMP_MANIFEST"
}

check_args

grep -q "status --uuid" "$BOSH_MANIFEST" && edit_manifest;

bundle install

bundle exec rake spec:unit

spec_files=($(find spec/system/ -type f))

for spec_file in "${spec_files[@]}"
do
  bundle exec rspec "$spec_file" --fail-fast
done
