#!/usr/bin/env bash

set -e -x

cd src/rabbitmq-cluster-migration-tool
DOCKER_IMAGE=cflondonservices/london-services-ci-rabbitmq:stable

docker logout

docker run \
      -v $PWD:/home/vcap/gopath/src/github.com/pivotal-cf/rabbitmq-cluster-migration-tool \
      -w /home/vcap/gopath/src/github.com/pivotal-cf/rabbitmq-cluster-migration-tool \
      $DOCKER_IMAGE ./scripts/test.sh
