#!/usr/bin/env bash

set -e

ROOT_DIR_PATH="$(cd "$(dirname "$0")"/.. && pwd)"
cd "$ROOT_DIR_PATH"
export GOPATH="$ROOT_DIR_PATH"

echo "Upgrade preparation"
pushd src/rabbitmq-upgrade-preparation
  scripts/run_tests
popd

echo "rabbitmq-adminn"
pushd src/rabbitmq-admin
  ginkgo -r
popd

echo "Bash scripts"
scripts/run-bash-tests

echo "Ruby unit tests"
scripts/bundle-with-env rake spec:unit
