#!/bin/bash
set -ex

. scripts/config/docker_image

RELEASE_GLOB=$1
shift

cp $RELEASE_GLOB .

docker run --rm \
  -e BUNDLE_GEM__FURY__IO=${BUNDLE_GEM__FURY__IO} \
  -v $PWD:$PWD \
  -w $PWD \
  -v "${PRIVATE_KEY}:/key" \
  $DOCKER_IMAGE \
  bash -c 'eval $(ssh-agent) && chmod 400 /key && ssh-add /key && bundle install && bundle exec rake --trace release_pipeline:update_release["git@github.com:pivotal-cf/p-rabbitmq","p-rabbitmq","*.tgz","cf-services-internal-builds","rabbitmq"]'
