#!/bin/bash
set -ex

. scripts/config/docker_image

docker run --rm \
  -e BUNDLE_GEM__FURY__IO=${BUNDLE_GEM__FURY__IO} \
  -v $PWD:$PWD \
  -w $PWD \
  $DOCKER_IMAGE \
  bash -c "bundle install && bundle exec rake --trace release_pipeline:upload[releases/**/*.tgz,${AWS_ACCESS_KEY_ID},${AWS_SECRET_ACCESS_KEY}]"

