#!/usr/bin/env bash
# ensure_dir_with_permissions
#
# @param directory name
#
# Creates  directory <directory name> if it doesn't exist
# sets the ownership recursively to vcap and
# changes the permissions to rwxr-x---
#
function ensure_dir_with_permissions() {
    local _dir=${1:?missing directory}
    local ownership=${2:-vcap:vcap}
    mkdir -p "${_dir}"
    chown -LR -P "$ownership" "$_dir"
    chmod 750 "${_dir}"
    chmod -R o-rwx "${_dir}"
}
