#!/usr/bin/env bash

set -e

CONFIG_DIR=$1

if [[ -z $CONFIG_DIR ]]
then
  echo "Usage: setup_syslog_forwarder [config dir]"
  exit 1
fi

# Need to overwrite the existing 00-syslog_forwarder.conf otherwise dupicate
# configuration will apply. Not sure how rsyslogd behaves in this kind of
# scenario so we thought it best to "remove" the problem.
cp $CONFIG_DIR/syslog_forwarder.conf /etc/rsyslog.d/00-syslog_forwarder.conf
